### PR TITLE
Update info for WeChat NFC

### PR DESCRIPTION
**Pull request by lihenggui**

### CODE REVIEW

**Comment by Mygod** [comment]
Thanks! I took it from here, and I suppose this needs updating too? https://github.com/lihenggui/blocker-general-rules/blob/ef864eee56b11fc8e52ac6792609c0325bff6b0a/rules/en/general.json#L5804

**Comment by lihenggui** [comment]
> Thanks! I took it from here, and I suppose this needs updating too?
> 
> https://github.com/lihenggui/blocker-general-rules/blob/ef864eee56b11fc8e52ac6792609c0325bff6b0a/rules/en/general.json#L5804

No, the description should match the component because you add a new component/library info.

**Comment by Mygod** [comment]
It was reused from here though? 👀 

https://github.com/lihenggui/blocker-general-rules/blob/ef864eee56b11fc8e52ac6792609c0325bff6b0a/rules/en/general.json#L1515

**Comment by lihenggui** [comment]
> Thanks! I took it from here, and I suppose this needs updating too?
> 
> https://github.com/lihenggui/blocker-general-rules/blob/ef864eee56b11fc8e52ac6792609c0325bff6b0a/rules/en/general.json#L5804

Correct, it needs updating. I missed that previously.

**Pull request merged**
